package interfaces.estudiantes;

import clases.estudiante;
import interfaces.CursosActualesDataModel;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amira Sony Vaio
 */
public class editarEstudiante extends javax.swing.JInternalFrame {

    private CursosActualesDataModel dataModel;
    private estudiante est;
    /**
     * Creates new form editarEstudiante
     */
    public editarEstudiante(String operacion) {
        dataModel = new CursosActualesDataModel();
        initComponents();
        btnEditar.setText(operacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelIdentificar = new javax.swing.JPanel();
        lblEstudiante = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelEstudiante = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtColegio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        panelCursosDisponibles = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCursosDisponibles = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panelIdentificar.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el estudiante"));
        panelIdentificar.setPreferredSize(new java.awt.Dimension(250, 46));
        panelIdentificar.setLayout(new java.awt.GridBagLayout());

        lblEstudiante.setText("Estudiante");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 9);
        panelIdentificar.add(lblEstudiante, gridBagConstraints);

        txtBuscar.setMinimumSize(new java.awt.Dimension(100, 25));
        txtBuscar.setName(""); // NOI18N
        txtBuscar.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        panelIdentificar.add(txtBuscar, gridBagConstraints);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        panelIdentificar.add(btnBuscar, gridBagConstraints);

        getContentPane().add(panelIdentificar);

        panelEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Del Estudiante"));
        panelEstudiante.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        panelEstudiante.add(jLabel1, gridBagConstraints);

        txtNombres.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 120;
        panelEstudiante.add(txtNombres, gridBagConstraints);

        jLabel2.setText("Apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panelEstudiante.add(jLabel2, gridBagConstraints);

        txtApellidos.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE_TRAILING;
        panelEstudiante.add(txtApellidos, gridBagConstraints);

        jLabel3.setText("Cedula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        panelEstudiante.add(jLabel3, gridBagConstraints);

        txtCedula.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 120;
        panelEstudiante.add(txtCedula, gridBagConstraints);

        jLabel4.setText("Fecha de Nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 9, 0, 6);
        panelEstudiante.add(jLabel4, gridBagConstraints);

        txtFechaNacimiento.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE_TRAILING;
        panelEstudiante.add(txtFechaNacimiento, gridBagConstraints);

        jLabel5.setText("Telefono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        panelEstudiante.add(jLabel5, gridBagConstraints);

        txtTelefono.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 120;
        panelEstudiante.add(txtTelefono, gridBagConstraints);

        jLabel6.setText("Genero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        panelEstudiante.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Colegio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        panelEstudiante.add(jLabel7, gridBagConstraints);

        txtColegio.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 120;
        panelEstudiante.add(txtColegio, gridBagConstraints);

        jLabel8.setText("Direccion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        panelEstudiante.add(jLabel8, gridBagConstraints);

        txtDireccion.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE_TRAILING;
        panelEstudiante.add(txtDireccion, gridBagConstraints);

        jLabel9.setText("Domicilio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        panelEstudiante.add(jLabel9, gridBagConstraints);

        txtDomicilio.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 120;
        panelEstudiante.add(txtDomicilio, gridBagConstraints);

        jLabel11.setText("Correo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        panelEstudiante.add(jLabel11, gridBagConstraints);

        txtCorreo.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        panelEstudiante.add(txtCorreo, gridBagConstraints);

        txtGenero.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelEstudiante.add(txtGenero, gridBagConstraints);

        getContentPane().add(panelEstudiante);

        panelCursosDisponibles.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursos Disponibles"));
        panelCursosDisponibles.setLayout(new java.awt.GridBagLayout());

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        panelCursosDisponibles.add(btnEditar, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelCursosDisponibles.add(btnCancelar, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(600, 100));
        jScrollPane1.setMinimumSize(null);

        tbCursosDisponibles.setModel(dataModel);
        tbCursosDisponibles.setMaximumSize(new java.awt.Dimension(600, 72));
        tbCursosDisponibles.setPreferredSize(new java.awt.Dimension(200, 72));
        jScrollPane1.setViewportView(tbCursosDisponibles);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelCursosDisponibles.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(panelCursosDisponibles);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String buscar = txtBuscar.getText();
        if(buscar.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Ingrese un nombre, apellido o numero de cedula");
        }
        
        boolean estNombre, estApellido, estCedula;
        estNombre = cargarDatosFormulario(estudiante.buscarPorNombre(buscar));
        estApellido = cargarDatosFormulario(estudiante.buscarPorApellido(buscar));
        estCedula = cargarDatosFormulario(estudiante.buscarPorCedula(buscar));
        
        if(!estNombre && !estApellido && !estCedula){
            JOptionPane.showMessageDialog(rootPane, "No se encontro el usuario a buscar");
            clearAllFields();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        String label = btnEditar.getText();
        switch(label){
            case "Editar":{
                if(label.equals("Editar")){
                    btnEditar.setText("Agregar");
                    txtNombres.setEditable(true);
                    txtApellidos.setEditable(true);
                    txtCedula.setEditable(true);
                    txtTelefono.setEditable(true);
                    txtColegio.setEditable(true);
                    txtDireccion.setEditable(true);
                    txtFechaNacimiento.setEditable(true);
                    txtCorreo.setEditable(true);
                    txtDomicilio.setEditable(true);
                    txtGenero.setEditable(true);

                }else{
                    String nombre,apellido,cedula,
                            telefono,colegio,direccion,
                            fecha,genero,correo,
                            domicilio;

//                    estudiante est;

                    nombre = txtNombres.getText();
                    apellido = txtApellidos.getText();
                    cedula = txtCedula.getText();
                    telefono = txtTelefono.getText();
                    colegio = txtColegio.getText();
                    direccion = txtDireccion.getText();
                    fecha = txtFechaNacimiento.getText();
                    correo = txtCorreo.getText();
                    domicilio = txtDomicilio.getText();
                    genero = txtGenero.getText();

                    if(nombre.isEmpty()){
                        txtNombres.setBorder(new LineBorder(Color.red));
                        if(apellido.isEmpty()){
                            txtApellidos.setBorder(new LineBorder(Color.red));
                            if(cedula.isEmpty()){
                                txtCedula.setBorder(new LineBorder(Color.red));
                                JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un valor en los campos correspondientes");
                            }else
                                JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un nombre y un apellido");
                        }else
                            if(cedula.isEmpty()){
                                txtCedula.setBorder(new LineBorder(Color.red));
                                JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un nombre y una cedula");
                            }else
                                JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un nombre");
                    }else{
                        if(apellido.isEmpty()){
                            txtApellidos.setBorder(new LineBorder(Color.red));
                            if(cedula.isEmpty()){
                                txtCedula.setBorder(new LineBorder(Color.red));
                                JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un apellido y la cedula");
                            }else
                                JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un apellido");
                        }else
                            if(cedula.isEmpty()){
                                txtCedula.setBorder(new LineBorder(Color.red));
                                JOptionPane.showMessageDialog(rootPane, "Ingrese la cedula");
                            }else{
                                this.est = new estudiante(nombre, apellido, cedula, fecha, telefono, 
                                        genero, colegio, direccion, domicilio, correo);
                                this.est.actualizar();
                                btnEditar.setText("Editar");
                            }
                    }
                }
            }break;
            case "Consultar":{
                this.setVisible(false);
            }break;
            case "Eliminar":{
                this.est.eliminar();
            }
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed
    
    private void clearAllFields(){
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCedula.setText("");
        txtTelefono.setText("");
        txtColegio.setText("");
        txtDireccion.setText("");
        txtFechaNacimiento.setText("");
        txtGenero.setText("");
        txtCorreo.setText("");
        txtDomicilio.setText("");
        dataModel = new CursosActualesDataModel();
        tbCursosDisponibles.setModel(dataModel);
        
    }
    
    public boolean cargarDatosFormulario(estudiante est){
        if(est != null){
            this.est = est;
            txtNombres.setText(est.getNombres());
            txtApellidos.setText(est.getApellidos());
            txtCedula.setText(est.getCedula());
            txtCorreo.setText(est.getCorreo());
            txtColegio.setText(est.getColegio());
            txtDireccion.setText(est.getDireccion());
            txtDomicilio.setText(est.getDomicilio());
            txtFechaNacimiento.setText(est.getFecha_nacimiento());
            txtGenero.setText(est.getGenero());
            txtTelefono.setText(est.getTelefono());
            
            int col = this.dataModel.getColumnCount();
            Object[] data = new Object[col];
            int id = 0;
            for (String materia: est.getCursosDisponibles()){
                data[0] = id;
                id++;
                data[1] = materia;
                dataModel.addRow(data);
            }
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JPanel panelCursosDisponibles;
    private javax.swing.JPanel panelEstudiante;
    private javax.swing.JPanel panelIdentificar;
    private javax.swing.JTable tbCursosDisponibles;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtColegio;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
