package interfaces.estudiantes;

import clases.estudiante;
import interfaces.CursosActualesDataModel;
import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author catfish
 */
public class Nuevoestudiante1 extends javax.swing.JInternalFrame {

    private int id;
    private LinkedList<String> cursosDisponibles;
    /**
     * Creates new form Nuevoestudiante
     */
    public Nuevoestudiante1() {
        dataModel = new CursosActualesDataModel();
        this.id = 0;
        cursosDisponibles = new LinkedList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        lblColegio = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblDomicilio = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        cbGenero = new javax.swing.JComboBox<>();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        cbColegio = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        cbCursos = new javax.swing.JComboBox<>();
        lblCursos = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCursosDisponibles = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo Estudiante");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(578, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Del Estudiante"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblNombres.setText("Nombres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        jPanel1.add(lblNombres, gridBagConstraints);

        txtNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombresFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 120;
        jPanel1.add(txtNombres, gridBagConstraints);

        lblApellidos.setText("Apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel1.add(lblApellidos, gridBagConstraints);

        txtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidosFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE_TRAILING;
        jPanel1.add(txtApellidos, gridBagConstraints);

        lblCedula.setText("Cedula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        jPanel1.add(lblCedula, gridBagConstraints);

        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCedulaFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 120;
        jPanel1.add(txtCedula, gridBagConstraints);

        lblFechaNacimiento.setText("Fecha de Nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 9, 0, 6);
        jPanel1.add(lblFechaNacimiento, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE_TRAILING;
        jPanel1.add(txtFechaNacimiento, gridBagConstraints);

        lblTelefono.setText("Telefono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        jPanel1.add(lblTelefono, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 120;
        jPanel1.add(txtTelefono, gridBagConstraints);

        lblGenero.setText("Genero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel1.add(lblGenero, gridBagConstraints);

        lblColegio.setText("Colegio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        jPanel1.add(lblColegio, gridBagConstraints);

        lblDireccion.setText("Direccion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel1.add(lblDireccion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE_TRAILING;
        jPanel1.add(txtDireccion, gridBagConstraints);

        lblDomicilio.setText("Domicilio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        jPanel1.add(lblDomicilio, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 120;
        jPanel1.add(txtDomicilio, gridBagConstraints);

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 71;
        gridBagConstraints.ipady = 2;
        jPanel1.add(cbGenero, gridBagConstraints);

        lblCorreo.setText("Correo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        jPanel1.add(lblCorreo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        jPanel1.add(txtCorreo, gridBagConstraints);

        cbColegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(cbColegio, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursos Disponibles"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        cbCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "INEVAL", "SENESCYT" }));
        cbCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 14, 14, 14);
        jPanel2.add(cbCursos, gridBagConstraints);

        lblCursos.setText("Cursos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 14, 14, 14);
        jPanel2.add(lblCursos, gridBagConstraints);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        jPanel2.add(btnAgregar, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        jPanel2.add(btnCancelar, gridBagConstraints);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 70));

        tbCursosDisponibles.setModel(dataModel);
        tbCursosDisponibles.setMaximumSize(new java.awt.Dimension(500, 70));
        tbCursosDisponibles.setMinimumSize(new java.awt.Dimension(500, 70));
        tbCursosDisponibles.setPreferredSize(new java.awt.Dimension(500, 70));
        jScrollPane1.setViewportView(tbCursosDisponibles);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String nombre,apellido,cedula,
                telefono,colegio,direccion,
                fecha,genero,correo,
                domicilio;
        
        estudiante est;
        
        nombre = txtNombres.getText();
        apellido = txtApellidos.getText();
        cedula = txtCedula.getText();
        telefono = txtTelefono.getText();
        colegio = cbColegio.getSelectedItem().toString();
        direccion = txtDireccion.getText();
        fecha = txtFechaNacimiento.getText();
        correo = txtCorreo.getText();
        domicilio = txtDomicilio.getText();
        genero = cbGenero.getSelectedItem().toString();
        
        if(nombre.isEmpty()){
            txtNombres.setBorder(new LineBorder(Color.red));
            if(apellido.isEmpty()){
                txtApellidos.setBorder(new LineBorder(Color.red));
                if(cedula.isEmpty()){
                    txtCedula.setBorder(new LineBorder(Color.red));
                    JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un valor en los campos correspondientes");
                }else
                    JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un nombre y un apellido");
            }else
                if(cedula.isEmpty()){
                    txtCedula.setBorder(new LineBorder(Color.red));
                    JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un nombre y una cedula");
                }else
                    JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un nombre");
        }else{
            if(apellido.isEmpty()){
                txtApellidos.setBorder(new LineBorder(Color.red));
                if(cedula.isEmpty()){
                    txtCedula.setBorder(new LineBorder(Color.red));
                    JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un apellido y la cedula");
                }else
                    JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un apellido");
            }else
                if(cedula.isEmpty()){
                    txtCedula.setBorder(new LineBorder(Color.red));
                    JOptionPane.showMessageDialog(rootPane, "Ingrese la cedula");
                }else{

                    est = new estudiante(nombre, apellido, cedula, fecha, telefono, 
                            genero, colegio, direccion, domicilio, correo);
                    est.setCursosDisponibles(cursosDisponibles);
//                    estudiante.estudiantes.add(est);
                    est.guardar();
                    JOptionPane.showMessageDialog(rootPane, "Se creo correctamente al estudiante");
                    int n = JOptionPane.showConfirmDialog(rootPane, "Desea agregar a otro usuario", "Confirmacion", JOptionPane.OK_CANCEL_OPTION);
                    if(n == JOptionPane.OK_OPTION){
                        clearAllFields();
                    }else{
                        this.setVisible(false);
                    }
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusGained
        // TODO add your handling code here:
        if(txtNombres.getBorder() instanceof LineBorder)
            txtNombres.setBorder(new LineBorder(Color.blue));
    }//GEN-LAST:event_txtNombresFocusGained

    private void txtApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusGained
        // TODO add your handling code here:
        if(txtApellidos.getBorder() instanceof LineBorder)
            txtApellidos.setBorder(new LineBorder(Color.blue));
    }//GEN-LAST:event_txtApellidosFocusGained

    private void txtCedulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusGained
        // TODO add your handling code here:
        if(txtCedula.getBorder() instanceof LineBorder)
            txtCedula.setBorder(new LineBorder(Color.blue));
    }//GEN-LAST:event_txtCedulaFocusGained

    private void cbCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursosActionPerformed
        // TODO add your handling code here:
        String option = cbCursos.getSelectedItem().toString();
        int col = this.dataModel.getColumnCount();
        Object[] data = new Object[col];
        
        if (!option.equals("-----------")) {
            data[0] = this.id;
            this.id++;
            data[1] = option;
            if(!this.cursosDisponibles.contains(option)){
                this.cursosDisponibles.add(option);
                this.dataModel.addRow(data);
            }
        } 
    }//GEN-LAST:event_cbCursosActionPerformed

    private void clearAllFields(){
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCedula.setText("");
        txtTelefono.setText("");
        cbColegio.setSelectedIndex(0);
        txtDireccion.setText("");
        txtFechaNacimiento.setText("");
        txtCorreo.setText("");
        txtDomicilio.setText("");
        dataModel = new CursosActualesDataModel();
        tbCursosDisponibles.setModel(dataModel);
        cursosDisponibles = new LinkedList<>();
        this.id = 0;
        cbCursos.setSelectedIndex(0);
    }
    
    private CursosActualesDataModel dataModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbColegio;
    private javax.swing.JComboBox<String> cbCursos;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblColegio;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCursos;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTable tbCursosDisponibles;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
